#!/bin/bash
#
# Copyright (c) 2020 by Thomas A. Early N7TAE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Uses the following environment variables 
# MREFD_CALLSIGN
# MREFD_NB_OF_MODULES
# MREFD_NB_OF_CLIENTS
# MREFD_LISTEN_IPV4
# MREFD_LISTEN_IPV6
# MREFD_DEBUG

# The following three vars should have multiple values separated by a comma
# MREFD_BLACKLIST		
# MREFD_WHITELIST
# MREFD_INTERLINK


rcfg='reflector.cfg'
srch='configure.h'
srcm='configure.mk'

# default values
callsign_d='CHNGME'
nummod_d=26
mclients_d=false
ip4addr_d='none'
ip6addr_d='none'
dbsupport_d=false


cd ~
rm -rf ~/mrefd
git clone https://github.com/n7tae/mrefd.git
cd ~/mrefd



WriteMemFile ()
{
	local file
	file="$rcfg"
	echo "# created on `date`"                                  > $file
	[ -z ${MREFD_CALLSIGN+x}    	] || echo   "callsign='$MREFD_CALLSIGN'"  	>> $file
	[ -z ${MREFD_NB_OF_MODULES+x}   ] || echo   "nummod=$MREFD_NB_OF_MODULES"   >> $file
	[ -z ${MREFD_NB_OF_CLIENTS+x}   ] || echo   "mclients=$MREFD_NB_OF_CLIENTS" >> $file
	[ -z ${MREFD_LISTEN_IPV4+x}     ] || echo   "ip4addr='$MREFD_LISTEN_IPV4'"  >> $file
	[ -z ${MREFD_LISTEN_IPV6+x}     ] || echo   "ipv6addr='$MREFD_LISTEN_IPV6'"  >> $file
	[ -z ${MREFD_DEBUG+x}   		] || echo   "dbsupport=$MREFD_DEBUG"   		>> $file
}

WriteSRCHFile ()
{
	local file m
	file="$srch"
	echo "// Created on `date`" > $file
	echo "#define CALLSIGN \"${MREFD_CALLSIGN}\"" >> $file
	if [ -z ${nummod+x} ]; then
		echo "#define NB_OF_MODULES ${nummod_d}" >> $file
	else
		echo "#define NB_OF_MODULES ${MREFD_NB_OF_MODULES}" >> $file
	fi
	if [ ! -z ${MREFD_LISTEN_IPV4+x} ]; then
		echo "#define LISTEN_IPV4 \"${MREFD_LISTEN_IPV4}\"" >> $file
	fi
	if [ ! -z ${MREFD_LISTEN_IPV6+x} ]; then
		echo "#define LISTEN_IPV6 \"${MREFD_LISTEN_IPV6}\"" >> $file
	fi
	if [ ! -z ${MREFD_NB_OF_CLIENTS+x} ]; then
		if [[ "$MREFD_NB_OF_CLIENTS" == "true" ]]; then
			echo "#define MREFD_NB_OF_CLIENTS" >> $file
		fi
	fi
}

WriteSRCMKFile ()
{
	local file
	file="$srcm"
	echo "# Created on `date`" > $file
	if [ -z ${MREFD_DEBUG+x} ]; then
		echo "debug = $dbsupport_d" >> $file
	else
		echo "debug = $MREFD_DEBUG" >> $file
	fi
}


WriteMemFile
WriteSRCHFile
WriteSRCMKFile

# extract whitelist, blacklist, and interlink

cp config/mrefd.whitelist .

if [ ! -z ${MREFD_WHITELIST+x} ]; then
	readarray -d "," -t strarr <<< "$MREFD_WHITELIST"
	for (( n=0; n < ${#strarr[*]}; n++))
	do
		echo "${strarr[n]}" >> mrefd.whitelist
	done
fi

cp config/mrefd.blacklist .

if [ ! -z ${MREFD_BLACKLIST+x} ]; then
	readarray -d "," -t strarr <<< "$MREFD_BLACKLIST"
	for (( n=0; n < ${#strarr[*]}; n++))
	do
		echo "${strarr[n]}" >> mrefd.blacklist
	done
fi

cp config/mrefd.interlink .

if [ ! -z ${MREFD_INTERLINK+x} ]; then
	readarray -d "," -t strarr <<< "$MREFD_INTERLINK"
	for (( n=0; n < ${#strarr[*]}; n++))
	do
		echo "${strarr[n]}" >> mrefd.interlink
	done
fi

# make some directories that the installer assumes to be there
mkdir /usr/local/etc
mkdir /etc/systemd/
mkdir /etc/systemd/system/

# make and install
make
make install

# the install will fail because no systemctl, and it can't start the service
# so we will start it ourselves.
~/mrefd/mrefd 
